# Generated by Django 5.2.7 on 2025-10-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='crested',
            new_name='created',
        ),
    ]
